/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author xp
 */
public class VentanaPokedex extends javax.swing.JFrame {

    //BufferedImage buffer = null; //DONDE COLOCO EL FONDO
    BufferedImage buffer1 = null; //DONDE SE PINTAN LOS POKEMON

    Image imagen1 = null; //POKEMON
    //Image imagen2 = null; //FONDO

    int contador = 0;
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) imagenPokemon.getGraphics();
        //Graphics2D g3 = (Graphics2D) fondo.getGraphics();
        //g3.drawImage(buffer, 0, 0, fondo.getWidth(), fondo.getHeight(), null);
        g2.drawImage(buffer1, 0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight(), null);

    }

    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {

        initComponents();
        this.setSize(1000,700);
        fondo.setSize(1000, 700);
        try {
            //imagen2 = ImageIO.read(getClass().getResource("/imagenes/Pokedex.jpg"));
            imagen1 = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
        } catch (IOException ex) {
            System.out.println("No se pudo cargar la imagen");
        }
        buffer1 = (BufferedImage) imagenPokemon.createImage(imagenPokemon.getWidth(), imagenPokemon.getHeight());
        //buffer = (BufferedImage) fondo.createImage(fondo.getWidth(), fondo.getHeight());
        Graphics2D g2 = buffer1.createGraphics();
        //dibujaFondo();
        dibujaPokemon(contador);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://127.0.0.1/pokedex", "root", "");
            estado = conexion.createStatement();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("HAY ERROR");
        }

    }
//PARA PONER EL FONDO
    //private void dibujaFondo() { //TE DIBUJA EL POKEMON QUE ESTA EN ESA POSICION
        //Graphics2D g3 = (Graphics2D) buffer.getGraphics();
       // g3.setColor(Color.WHITE); //PINTA EL FONDO BLANCO
       // g3.drawImage(imagen2, 0,0,fondo.getWidth(),fondo.getHeight(),null);
   // }

    private void dibujaPokemon(int posicion) { //TE DIBUJA EL POKEMON QUE ESTA EN ESA POSICION
        int fila = posicion / 31;
        int columna = posicion % 31;
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.WHITE); //PINTA EL FONDO BLANCO
        g2.fillRect(0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight());
        g2.drawImage(imagen1, 0 // POSICION X INICIAL EN EL JPANEL
                ,
                 0 // POSICION Y INICIAL EN EL JPANEL
                ,
                 imagenPokemon.getWidth(), //ANCHO DEL JPANEL
                imagenPokemon.getHeight(), //ALTO DEL JPANEL
                columna * 96, //POSICION INICIAL X DENTRO DE LA IMAGEN DE LOS POKEMON
                fila * 96, //POSICION INICIAL Y DENTRO DE LA IMAGEN DE LOS POKEMON
                columna * 96 + 96, //POSICION FINAL X
                fila * 96 + 96, null); //POSICION FINAL Y
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        imagenPokemon = new javax.swing.JPanel();
        derecha = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        nombreNombre = new javax.swing.JLabel();
        nombrePokemon = new javax.swing.JLabel();
        alturaPesoNombre = new javax.swing.JLabel();
        altura = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        habilidadNombre = new javax.swing.JLabel();
        habilidad = new javax.swing.JLabel();
        especieNombre = new javax.swing.JLabel();
        especie = new javax.swing.JLabel();
        habitatNombre = new javax.swing.JLabel();
        habitat = new javax.swing.JLabel();
        tiposNombre = new javax.swing.JLabel();
        tipo1 = new javax.swing.JLabel();
        tipo2 = new javax.swing.JLabel();
        prePosNombre = new javax.swing.JLabel();
        preEvolucion = new javax.swing.JLabel();
        posEvolucion = new javax.swing.JLabel();
        movimientosNombre = new javax.swing.JLabel();
        movimiento1 = new javax.swing.JLabel();
        movimiento2 = new javax.swing.JLabel();
        movimiento3 = new javax.swing.JLabel();
        movimiento4 = new javax.swing.JLabel();
        descripcionNombre = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        fondito = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        fondo.add(imagenPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 290, 190));

        derecha.setBackground(new java.awt.Color(255, 255, 0));
        derecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        derecha.setForeground(new java.awt.Color(255, 0, 0));
        derecha.setText(">");
        derecha.setBorder(null);
        derecha.setOpaque(false);
        derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaActionPerformed(evt);
            }
        });
        fondo.add(derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 60, 40));

        izquierda.setBackground(new java.awt.Color(255, 255, 0));
        izquierda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        izquierda.setForeground(new java.awt.Color(255, 0, 0));
        izquierda.setText("<");
        izquierda.setBorder(null);
        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });
        fondo.add(izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 60, 40));

        nombreNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nombreNombre.setForeground(new java.awt.Color(204, 0, 0));
        nombreNombre.setText("NOMBRE");
        fondo.add(nombreNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 50, 20));

        nombrePokemon.setBackground(new java.awt.Color(255, 255, 255));
        nombrePokemon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombrePokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrePokemon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        nombrePokemon.setOpaque(true);
        fondo.add(nombrePokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 90, 30));

        alturaPesoNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alturaPesoNombre.setForeground(new java.awt.Color(204, 0, 0));
        alturaPesoNombre.setText("ALTURA/PESO");
        fondo.add(alturaPesoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 160, -1, -1));

        altura.setBackground(new java.awt.Color(255, 255, 255));
        altura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        altura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        altura.setOpaque(true);
        fondo.add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 30, 32));

        peso.setBackground(new java.awt.Color(255, 255, 255));
        peso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        peso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        peso.setOpaque(true);
        fondo.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 30, 32));

        habilidadNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        habilidadNombre.setForeground(new java.awt.Color(204, 0, 0));
        habilidadNombre.setText("HABILIDAD");
        fondo.add(habilidadNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 164, 70, 20));

        habilidad.setBackground(new java.awt.Color(255, 255, 255));
        habilidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        habilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        habilidad.setOpaque(true);
        fondo.add(habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 80, 32));

        especieNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        especieNombre.setForeground(new java.awt.Color(204, 0, 0));
        especieNombre.setText("ESPECIE");
        fondo.add(especieNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 70, 20));

        especie.setBackground(new java.awt.Color(255, 255, 255));
        especie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        especie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        especie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        especie.setOpaque(true);
        fondo.add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 120, 32));

        habitatNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        habitatNombre.setForeground(new java.awt.Color(204, 0, 0));
        habitatNombre.setText("HABITAT");
        fondo.add(habitatNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 214, 50, 20));

        habitat.setBackground(new java.awt.Color(255, 255, 255));
        habitat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        habitat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habitat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        habitat.setOpaque(true);
        fondo.add(habitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 130, 32));

        tiposNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tiposNombre.setForeground(new java.awt.Color(204, 0, 0));
        tiposNombre.setText("TIPOS");
        fondo.add(tiposNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 50, 20));

        tipo1.setBackground(new java.awt.Color(255, 255, 255));
        tipo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        tipo1.setOpaque(true);
        fondo.add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 80, 32));

        tipo2.setBackground(new java.awt.Color(255, 255, 255));
        tipo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        tipo2.setOpaque(true);
        fondo.add(tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 70, 32));

        prePosNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prePosNombre.setForeground(new java.awt.Color(204, 0, 0));
        prePosNombre.setText("PRE/POS. EVL");
        fondo.add(prePosNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        preEvolucion.setBackground(new java.awt.Color(255, 255, 255));
        preEvolucion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        preEvolucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preEvolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        preEvolucion.setOpaque(true);
        fondo.add(preEvolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 40, 32));

        posEvolucion.setBackground(new java.awt.Color(255, 255, 255));
        posEvolucion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        posEvolucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posEvolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        posEvolucion.setOpaque(true);
        fondo.add(posEvolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 40, 32));

        movimientosNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        movimientosNombre.setForeground(new java.awt.Color(204, 0, 0));
        movimientosNombre.setText("MOVIMIENTOS");
        fondo.add(movimientosNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 80, 20));

        movimiento1.setBackground(new java.awt.Color(255, 255, 255));
        movimiento1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        movimiento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movimiento1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        movimiento1.setOpaque(true);
        fondo.add(movimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 120, 32));

        movimiento2.setBackground(new java.awt.Color(255, 255, 255));
        movimiento2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        movimiento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movimiento2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        movimiento2.setOpaque(true);
        fondo.add(movimiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 120, 32));

        movimiento3.setBackground(new java.awt.Color(255, 255, 255));
        movimiento3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        movimiento3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movimiento3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        movimiento3.setOpaque(true);
        fondo.add(movimiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 120, 32));

        movimiento4.setBackground(new java.awt.Color(255, 255, 255));
        movimiento4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        movimiento4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movimiento4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        movimiento4.setOpaque(true);
        fondo.add(movimiento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 120, 32));

        descripcionNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descripcionNombre.setForeground(new java.awt.Color(204, 0, 0));
        descripcionNombre.setText("DESCRIPCION");
        fondo.add(descripcionNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 424, 80, 20));

        descripcion.setBackground(new java.awt.Color(255, 255, 255));
        descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        descripcion.setOpaque(true);
        fondo.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 260, 60));

        fondito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pokedex.jpg"))); // NOI18N
        fondito.setOpaque(true);
        fondo.add(fondito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaActionPerformed

        try {
            resultadoConsulta = estado.executeQuery("select * from pokemon where id=" + (contador + 1));
            if (resultadoConsulta.next()) {
                nombrePokemon.setText(resultadoConsulta.getString(2));
                altura.setText(resultadoConsulta.getString(3));
                peso.setText(resultadoConsulta.getString(4));
                especie.setText(resultadoConsulta.getString(5));
                habitat.setText(resultadoConsulta.getString(6));
                tipo1.setText(resultadoConsulta.getString(7));
                tipo2.setText(resultadoConsulta.getString(8));
                habilidad.setText(resultadoConsulta.getString(9));
                movimiento1.setText(resultadoConsulta.getString(10));
                movimiento2.setText(resultadoConsulta.getString(11));
                movimiento3.setText(resultadoConsulta.getString(12));
                movimiento4.setText(resultadoConsulta.getString(13));
                preEvolucion.setText(resultadoConsulta.getString(14));
                posEvolucion.setText(resultadoConsulta.getString(15));
                descripcion.setText(resultadoConsulta.getString(16));
            } else {
                nombrePokemon.setText("X");
                altura.setText("X");
                peso.setText("X");
                especie.setText("X");
                habitat.setText("X");
                tipo1.setText("X");
                tipo2.setText("X");
                habilidad.setText("X");
                movimiento1.setText("X");
                movimiento2.setText("X");
                movimiento3.setText("X");
                movimiento4.setText("X");
                preEvolucion.setText("X");
                posEvolucion.setText("X");
                descripcion.setText("X");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        contador++;
        if (contador >= 649) {
            contador = 649;
        }
        dibujaPokemon(contador-1);
    }//GEN-LAST:event_derechaActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
        try {
            resultadoConsulta = estado.executeQuery("select * from pokemon where id=" + (contador));
            if (resultadoConsulta.next()) {
                nombrePokemon.setText(resultadoConsulta.getString(2));
                altura.setText(resultadoConsulta.getString(3));
                peso.setText(resultadoConsulta.getString(4));
                especie.setText(resultadoConsulta.getString(5));
                habitat.setText(resultadoConsulta.getString(6));
                tipo1.setText(resultadoConsulta.getString(7));
                tipo2.setText(resultadoConsulta.getString(8));
                habilidad.setText(resultadoConsulta.getString(9));
                movimiento1.setText(resultadoConsulta.getString(10));
                movimiento2.setText(resultadoConsulta.getString(11));
                movimiento3.setText(resultadoConsulta.getString(12));
                movimiento4.setText(resultadoConsulta.getString(13));
                preEvolucion.setText(resultadoConsulta.getString(14));
                posEvolucion.setText(resultadoConsulta.getString(15));
                descripcion.setText(resultadoConsulta.getString(16));
            } else {
                nombrePokemon.setText("X");
                altura.setText("X");
                peso.setText("X");
                especie.setText("X");
                habitat.setText("X");
                tipo1.setText("X");
                tipo2.setText("X");
                habilidad.setText("X");
                movimiento1.setText("X");
                movimiento2.setText("X");
                movimiento3.setText("X");
                movimiento4.setText("X");
                preEvolucion.setText("X");
                posEvolucion.setText("X");
                descripcion.setText("X");
            }
        } catch (SQLException ex) {
        }
        contador--;
        if (contador < 0) {
            contador = 0;
        }
        dibujaPokemon(contador);
    }//GEN-LAST:event_izquierdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altura;
    private javax.swing.JLabel alturaPesoNombre;
    private javax.swing.JButton derecha;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel descripcionNombre;
    private javax.swing.JLabel especie;
    private javax.swing.JLabel especieNombre;
    private javax.swing.JLabel fondito;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel habilidad;
    private javax.swing.JLabel habilidadNombre;
    private javax.swing.JLabel habitat;
    private javax.swing.JLabel habitatNombre;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel movimiento1;
    private javax.swing.JLabel movimiento2;
    private javax.swing.JLabel movimiento3;
    private javax.swing.JLabel movimiento4;
    private javax.swing.JLabel movimientosNombre;
    private javax.swing.JLabel nombreNombre;
    private javax.swing.JLabel nombrePokemon;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel posEvolucion;
    private javax.swing.JLabel preEvolucion;
    private javax.swing.JLabel prePosNombre;
    private javax.swing.JLabel tipo1;
    private javax.swing.JLabel tipo2;
    private javax.swing.JLabel tiposNombre;
    // End of variables declaration//GEN-END:variables
}
